// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	// Start the stream of numbers
	Doubler(ctx context.Context, in *Request, opts ...grpc.CallOption) (Service_DoublerClient, error)
	Random(ctx context.Context, in *Request, opts ...grpc.CallOption) (Service_RandomClient, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Doubler(ctx context.Context, in *Request, opts ...grpc.CallOption) (Service_DoublerClient, error) {
	stream, err := c.cc.NewStream(ctx, &Service_ServiceDesc.Streams[0], "/ably.v1.Service/Doubler", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceDoublerClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Service_DoublerClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type serviceDoublerClient struct {
	grpc.ClientStream
}

func (x *serviceDoublerClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *serviceClient) Random(ctx context.Context, in *Request, opts ...grpc.CallOption) (Service_RandomClient, error) {
	stream, err := c.cc.NewStream(ctx, &Service_ServiceDesc.Streams[1], "/ably.v1.Service/Random", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceRandomClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Service_RandomClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type serviceRandomClient struct {
	grpc.ClientStream
}

func (x *serviceRandomClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility
type ServiceServer interface {
	// Start the stream of numbers
	Doubler(*Request, Service_DoublerServer) error
	Random(*Request, Service_RandomServer) error
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (UnimplementedServiceServer) Doubler(*Request, Service_DoublerServer) error {
	return status.Errorf(codes.Unimplemented, "method Doubler not implemented")
}
func (UnimplementedServiceServer) Random(*Request, Service_RandomServer) error {
	return status.Errorf(codes.Unimplemented, "method Random not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_Doubler_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServiceServer).Doubler(m, &serviceDoublerServer{stream})
}

type Service_DoublerServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type serviceDoublerServer struct {
	grpc.ServerStream
}

func (x *serviceDoublerServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func _Service_Random_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServiceServer).Random(m, &serviceRandomServer{stream})
}

type Service_RandomServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type serviceRandomServer struct {
	grpc.ServerStream
}

func (x *serviceRandomServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ably.v1.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Doubler",
			Handler:       _Service_Doubler_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Random",
			Handler:       _Service_Random_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "server.proto",
}
